CREATE TABLE "patients" (
	"id" serial PRIMARY KEY NOT NULL,
	"first_name" text NOT NULL,
	"last_name" text NOT NULL,
	"date_of_birth" text NOT NULL,
	"mrn" text,
	"medicaid_id" text,
	"medicare_id" text,
	"managed_care_plan_id" text,
	"payer_type" text NOT NULL,
	"housing_status" text NOT NULL,
	"qr_code_wallet" text,
	"adt_status" text DEFAULT 'unknown' NOT NULL,
	"ecm_enrolled" boolean DEFAULT false NOT NULL,
	"athena_patient_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "encounters" (
	"id" serial PRIMARY KEY NOT NULL,
	"patient_id" integer NOT NULL,
	"provider_id" integer,
	"encounter_date" timestamp NOT NULL,
	"pos_code" text DEFAULT '27' NOT NULL,
	"em_code" text NOT NULL,
	"diagnosis_codes" text[] DEFAULT '{}' NOT NULL,
	"sdoh_z_codes" text[] DEFAULT '{}' NOT NULL,
	"clinical_notes" text,
	"location_description" text,
	"gps_lat" double precision,
	"gps_lng" double precision,
	"gps_accuracy" double precision,
	"status" text DEFAULT 'draft' NOT NULL,
	"is_offline_capture" boolean DEFAULT false NOT NULL,
	"offline_timestamp" timestamp,
	"sync_timestamp" timestamp,
	"crypto_hash" text,
	"payer_type" text NOT NULL,
	"reimbursement_rate" text DEFAULT 'non_facility' NOT NULL,
	"estimated_reimbursement" double precision,
	"claim_id" integer,
	"athena_encounter_id" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
